require:
  - rubocop-rake
  - rubocop-rspec

inherit_mode:
  merge:
    - Exclude

AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable
  Exclude:
    - gem_rbs_collection/**/*

Metrics/BlockLength:
  Exclude:
    - spec/**/*

Metrics/MethodLength:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma

RSpec/ExampleLength:
  Enabled: false

RSpec/FilePath:
  CustomTransform:
    JaLC: jalc

RSpec/MultipleExpectations:
  Enabled: false
