name: Ruby

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    name: Ruby ${{ matrix.ruby }} / ${{ matrix.gemfile }}

    strategy:
      matrix:
        ruby:
          - "2.7"
          - "3.0"
          - "3.1"
        gemfile:
          - "gemfiles/faraday_1.gemfile"
          - "Gemfile"
    
    env:
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}

    steps:
      - uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Run the default task
        run: bundle exec rake
