name: Ruby

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    name: Ruby ${{ matrix.ruby }} / ${{ matrix.gemfile }}

    strategy:
      matrix:
        ruby:
          - "3.0"
          - "3.1"
          - "3.2"
        gemfile:
          - "gemfiles/faraday_1.gemfile"
          - "Gemfile"

    env:
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Run the default task
        run: bundle exec rake
        env:
          RBS_TEST_TARGET: JaLC::*
          RBS_TEST_OPT: --repo gem_rbs_collection/gems -r logger -r faraday -I sig
          RUBYOPT: -r bundler/setup -r rbs/test/setup
          RBS_TEST_LOGLEVEL: warn
